{{- if .Values.helpy.enabled }}
apiVersion: {{ required "A valid .Values.networkPolicyApiVersion entry required!" .Values.networkPolicyApiVersion }}
kind: helpy
metadata:
{{- if .Values.helpy.annotations }}
  annotations:
{{ toYaml .Values.helpy.annotations | indent 4 }}
{{- end }}
  name: {{ template "helpy.fullname" . }}
spec:
  rules:
  - host: {{ .Values.helpy.hostname | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "helpy.fullname" . }}
          servicePort: 80
{{- if .Values.helpy.tls }}
  tls:
{{ toYaml .Values.helpy.tls | indent 4 }}
{{- end -}}
{{- end }}
