apiVersion: v1
kind: Service
metadata:
  name: {{ template "helpy.fullname" . }}
  labels:
    app: {{ template "helpy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  type: {{ .Values.serviceType }}
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: {{ template "helpy.fullname" . }}
  {{ if eq .Values.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.service.loadBalancerSourceRanges }}
  {{ end }}
